# Generated by Django 5.1.1 on 2024-09-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('projects', 'Projects'), ('academic', 'Academic')], max_length=10, verbose_name='type'),
        ),
    ]
