FROM python:3.11.4-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

ARG DJANGO_DEBUG
ENV DJANGO_DEBUG = ${DJANGO_DEBUG}
ARG DJANGO_SECRET_KEY
ENV DJANGO_SECRET_KEY = ${DJANGO_SECRET_KEY}
ARG DJANGO_ALLOWED_HOSTS
ENV DJANGO_ALLOWED_HOSTS = ${DJANGO_ALLOWED_HOSTS}
ARG DJANGO_CSRF_TRUSTED_ORIGINS
ENV DJANGO_CSRF_TRUSTED_ORIGINS = ${DJANGO_CSRF_TRUSTED_ORIGINS}
ARG DJANGO_SECURE_HSTS_SECONDS
ENV DJANGO_SECURE_HSTS_SECONDS = ${DJANGO_SECURE_HSTS_SECONDS}
ARG DJANGO_SECURE_SSL_REDIRECT
ENV DJANGO_SECURE_SSL_REDIRECT = ${DJANGO_SECURE_SSL_REDIRECT}
ARG DJANGO_SESSION_COOKIE_SECURE
ENV DJANGO_SESSION_COOKIE_SECURE = ${DJANGO_SESSION_COOKIE_SECURE}
ARG DJANGO_CSRF_COOKIE_SECURE
ENV DJANGO_CSRF_COOKIE_SECURE = ${DJANGO_CSRF_COOKIE_SECURE}
ARG DJANGO_SECURE_HSTS_PRELOAD
ENV DJANGO_SECURE_HSTS_PRELOAD = ${DJANGO_SECURE_HSTS_PRELOAD}

ARG DJANGO_SUPERUSER_USERNAME
ENV DJANGO_SUPERUSER_USERNAME = ${DJANGO_SUPERUSER_USERNAME}
ARG DJANGO_SUPERUSER_PASSWORD
ENV DJANGO_SUPERUSER_PASSWORD = ${DJANGO_SUPERUSER_PASSWORD}
ARG DJANGO_SUPERUSER_EMAIL
ENV DJANGO_SUPERUSER_EMAIL = ${DJANGO_SUPERUSER_EMAIL}

ARG PG_USER
ENV PG_USER = ${PG_USER}
ARG PG_PASSWORD
ENV PG_PASSWORD = ${PG_PASSWORD}
ARG PG_DB
ENV PG_DB = ${PG_DB}
ARG PG_PORT
ENV PG_PORT = ${PG_PORT}
ARG PG_HOST
ENV PG_HOST = ${PG_HOST}


ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $HOME
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/staticfiles
RUN mkdir $APP_HOME/mediafiles

WORKDIR $APP_HOME

COPY ./src $APP_HOME

COPY . .

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "blog.wsgi:application"]
