services:
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput &&
                      python manage.py collectstatic --noinput &&
                      python manage.py createsuperuser --noinput &&
                      gunicorn blog.wsgi --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 20s
      retries: 10
  nginx:
    build: ./nginx/
    ports:
      - "1337:80"
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles

volumes:
  postgres_data:
  static_volume:
  media_volume: