# Generated by Django 5.1.1 on 2024-09-05 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_personalinfotranslation_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfotranslation',
            name='personal_life',
            field=models.TextField(default='', verbose_name='personal_life'),
            preserve_default=False,
        ),
    ]
