# Generated by Django 5.1.1 on 2024-09-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_personalinfotranslation_personal_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(default='luizhenriquebirckvicari@gmail.com', max_length=254, verbose_name='e-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(default='github.com/LuizHVicari', verbose_name='github link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinfotranslation',
            name='personal_life',
            field=models.TextField(verbose_name='personal life'),
        ),
    ]
