# Generated by Django 5.1.1 on 2024-09-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_personalinfo_email_personalinfo_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='github',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='phone_number',
        ),
    ]
