# Generated by Django 5.1.1 on 2024-09-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_abilities_personalinfo_abilities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abilities',
            new_name='Ability',
        ),
        migrations.RenameModel(
            old_name='AbilitiesTranslation',
            new_name='AbilityTranslation',
        ),
        migrations.AlterModelTable(
            name='abilitytranslation',
            table='core_ability_translation',
        ),
    ]
