# Generated by Django 5.1.1 on 2024-09-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_abilities_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='key_name',
            field=models.CharField(default='', help_text='the name that will appear on the admin page', max_length=50, verbose_name='key name'),
            preserve_default=False,
        ),
    ]
