# Generated by Django 5.1.1 on 2024-09-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_ability_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='weight',
            field=models.IntegerField(default=0, help_text='order in wich it will appear on the index page', verbose_name='weight'),
        ),
    ]
